project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Problem Solvers Guild Blog"
  favicon: "favicon.ico"
  google-analytics: "G-FJDC3EN75W"
  navbar:
    right:
      - icon: github
        href: https://github.com/orgs/ProblemSolversGuild
      - icon: linkedin
        href: https://www.linkedin.com/company/theproblemsolversguild

format:
  html:
    theme:
      light: cosmo
      dark: [darkly, dark.scss]
    respect-user-color-scheme: true
    css: styles.css
    # Inserts the conditional back link on every page.
    include-after-body: back-link.html



