project:
  type: website

website:
  title: "Problem Solvers Guild Blog"
  google-analytics: "G-FJDC3EN75W"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/orgs/ProblemSolversGuild
      - icon: twitter
        href: https://twitter.com/TPSG_io
      - icon: linkedin
        href: https://www.linkedin.com/company/theproblemsolversguild

format:
  html:
    theme: cosmo
    css: styles.css



